### ISSUE TITLE
AddAccount exports [object Object]

### ISSUE THREAD

**Issue by nsjames** [dfuse-io/dfuseeos-migrator-client#1]
Looks like `fs` is trying to write a JSON object as-is without validating its type first, which causes it to be written as [object Object] in text form. 

https://github.com/dfuse-io/dfuseeos-migrator-client/blob/master/src/navigation.ts#L85

Doing `JSON.stringify` on the `account.data` first solves this, but might not always be the expected result as these could be Buffers as well.

**Comment by jubeless** [comment]
Fixed the issue

https://github.com/dfuse-io/dfuseeos-migrator-client/blob/be53c5ca415358f825776715274469acbca3573d/src/navigation.ts#L90-L97
