### ISSUE TITLE
AddAccount doesn't allow specifying permissions structures

### ISSUE THREAD

**Issue by nsjames** [dfuse-io/dfuseeos-migrator-client#2]
https://github.com/dfuse-io/dfuseeos-migrator-client/blob/master/src/migrator.ts#L39

Looks like this only supports `limits`, `wasm` and `abi`, but not the `data` param. Since `writeAccount` is also not an exported member of the library there is no way to force a permission structure for new accounts.

**Comment by jubeless** [comment]
We added the ability to specify permissions and link auth structure when creating a new account:

https://github.com/dfuse-io/dfuseeos-migrator-client/blob/be53c5ca415358f825776715274469acbca3573d/src/migrator.ts#L39-L47
